# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarQuitar():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarQuitar(self):
    # Test name: Agregar_Quitar
    # Step # | name | target | value
    # 1 | open | http://localhost:8000/inventario.html | 
    self.driver.get("http://localhost:8000/inventario.html")
    # 2 | setWindowSize | 1094x1392 | 
    self.driver.set_window_size(1094, 1392)
    # 3 | click | css=button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    # 4 | click | css=button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    # 5 | click | css=button:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 6 | click | css=button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    # 7 | click | css=button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    # 8 | doubleClick | css=button:nth-child(3) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 9 | click | css=button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    # 10 | click | css=button:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 11 | click | css=button:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 12 | doubleClick | css=button:nth-child(4) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 13 | click | css=button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    # 14 | click | css=button:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 15 | click | css=button:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 16 | doubleClick | css=button:nth-child(4) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 17 | click | css=button:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 18 | close |  | 
    self.driver.close()
  
